### ISSUE TITLE
css related

### ISSUE THREAD

**Issue by RAJEEVKUMAR9598** [gauran12/Ethereal-One-Page-web#4]
HII @gauran12 can i provide a best css for your website..

**Comment by RAJEEVKUMAR9598** [comment]
Please assign this task me ..

**Comment by hiteshdate** [comment]
Hello @gauran12, While checking out your css layout it looks awesome but instead of horizontal view we can add vertical view which make it more readable , attractive and easy to understand .Please assign me this issue for making the css part in more fruitful way.
